# Generated by Django 5.2.1 on 2025-06-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_email_port_emailsettings_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze_badges', models.IntegerField(default=0)),
                ('silver_badges', models.IntegerField(default=0)),
                ('gold_badges', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
