# Generated by Django 5.2.1 on 2025-06-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='hours',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_duration', models.FloatField()),
                ('break_duration', models.FloatField()),
                ('websites_blocked', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
