# Generated by Django 5.2.1 on 2025-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='hours',
            field=models.FloatField(),
        ),
    ]
