# Generated by Django 5.2.1 on 2025-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_userdata_hours_sessiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondetails',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
