# Generated by Django 5.2.1 on 2025-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_sessiondetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetails',
            name='name',
            field=models.CharField(default='Unnamed Session', max_length=100),
        ),
    ]
