# Generated by Django 5.2.1 on 2025-06-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_sessiondetails_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionDetails',
        ),
    ]
